config/routes.rb
Backlog::Application.routes.draw do
  get "dashboard/login"

  get "dashboard/logout"

  get "dashboard/index"

  post "backlog/sort"
  post "backlog/prioritize"
  post "backlog/progress"

  resources :categories do
    resources :items
  end
  delete "items/destroy" # JavaScript drop_receiving_element

  root :to => "dashboard#index"

end

app/controllers/dashboard_controller.rb
require 'lib/git'
require 'lib/backlog_rc'

class DashboardController < ApplicationController
  
  def initialize
    @git = Backlog::Git.instance.git
    @rc = Backlog::BacklogRc.instance
    super
  end

  def login
  end

  def logout
  end

  def index
    @categories = Category.all
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<div class="grid_12" id="header">
Name: <span id="name"><%= @git.config('user.name') %></span>
EMail: <span id="email"><%= @git.config('user.email') %></span>
Dir: <span id="home"><%= @rc.home %></span>
</div>
<div class="clear"></div>

<div class="grid_12">
<h1>Backlog - Dashboard</h1>
</div>

<% [:info, :error].each do |key| %>
  <% if flash[key] %>
    <div class="grid_12" class="<%= key %>" id="flash">
    <%= flash[key] %>
    <% flash[key] = nil %>
    </div>
  <% end %>
<% end %>

  <% @categories.each do |category|
       cid = category.id %>
  <div class="grid_3">
    <div class="itemlist" id="<%=cid%>">
      <h2><%=category.name%></h2>
      <div class="itemlist" id="<%=cid%>_list">
        <% category.items.each do |item|
	   iid = item.id %>
          <div class="item" id="<%=cid%>_<%=iid%>">
            <div class="item_link">
              <%= link_to item.subject, category_items_path(category,item) %>
            </div>
            <%= draggable_element "#{cid}_#{iid}", :revert => true %>
            <a class="item_handle" href="#" onclick="return false"> </a>
          </div>
        <% end %>
      </div>
      <%= sortable_element "#{cid}_list", :url => { :controller =>
"backlog", :action => "sort" }, :tag => "div", :elements => "$$('.item')",
:handles => "$$('.item_handle')",
:constraint => :vertical %>
    </div>
  </div>
  <% end %>

<div class="clear"></div>
<div class="grid_12" id="footer">
  <div class="grid_1">
    <div class="button_new">
      <%= link_to "new", new_category_item_url(@categories.first) %>
    </div>
  </div>
  <div class="grid_10"></div>
  <div class="grid_1" id="trash">Trash</div>
</div>
<%= drop_receiving_element "trash", :url => { :controller => "items", :action => "destroy" }, :confirm => "Really delete?", :loading => visual_effect(:fade)  %>

app/views/dashboard/login.html.erb
<h1>Backlog#login</h1>
<p>Find me in app/views/backlog/login.html.erb</p>

app/views/dashboard/logout.html.erb
<h1>Backlog#logout</h1>
<p>Find me in app/views/backlog/logout.html.erb</p>